version: "3"
services:
  client:
    build:
      context: .
      dockerfile: ./docker/client/Dockerfile
    volumes:
      - ./client:/client
    command: sh -c "PORT=3000 yarn start"
    ports:
      - 3000:3000
    stdin_open: true


  server:
    container_name: "server"
    volumes:
      - ./server:/server
    build:
      context: .
      dockerfile: ./docker/server/Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - db

  db:
    image: postgres:14-alpine
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    env_file:
      - ./server/.env
    ports:
      - 5432:5432
